
# # ----------------------------------------------------------------
# # Course: EECS 110, Northwestern University
# # Term: Winter 2019
# # Autogenerated from: "../lectures/lecture_14/notebooks/Looking at Congress.ipynb"
# # 
# # Note: Each example is commented out. To uncomment, highlight
# # the area you want to uncomment and type "cmd /" (which both adds
# # and removes comments).
# # ----------------------------------------------------------------

# import pandas as pd
# %matplotlib inline
# 
# # Load legislators-current.csv file from disk 
# # and convert the birthday column to a date column:
# legislators = pd.read_csv("../data/legislators-current.csv", encoding="latin")
# legislators['birthday'] = pd.to_datetime(legislators['birthday'], format='%m/%d/%Y')



# # --------------------------------------------------------------------------------
# # ## Please complete the following tasks
# # 
# # 1. In a new cell, output a data frame that only includes members of the legislature from a state of your choosing (e.g. "Only show me senators and representatives from Illinois").
# # 2. In a new cell, output the 5 **oldest senators** (type == 'sen')
# # 3. In a new cell, output the 5 **youngest** people in the **house of representatives** (type == 'rep')
# # 4. In a new cell, output a dataframe showing the number of men and women in congress by state.
# # 5. In a new cell, output the representative counts for each state in descending order.
# # 6. In a new cell, make a **bar chart** of the states with the most representatives and the number of representatives they have.
# # --------------------------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # ### preview table
# # --------------------------------------------------------------------------------

# legislators.head(10)



# # --------------------------------------------------------------------------------
# # ### Exercise 1
# # Output a data frame that only includes members of the legislature from a state of your choosing (e.g. "Only show me senators and representatives from Illinois").
# # 
# # Hint: create a rule, and then filter the table using the rule. See the Evanston Inspection example for details.
# # --------------------------------------------------------------------------------

# # Your code here...



# # --------------------------------------------------------------------------------
# # ### Exercise 2
# # Output the 5 oldest senators. Hint: You will need to create a senate filter and then sort by birthday descending.
# # --------------------------------------------------------------------------------

# # Your code here...



# # --------------------------------------------------------------------------------
# # ### Exercise 3
# # Output the 5 youngest people in the house of representatives. Output the 5 oldest senators. Hint: You will need to create a house of representatives filter and then sort by birthday ascending.
# # --------------------------------------------------------------------------------

# # Your code here...



# # --------------------------------------------------------------------------------
# # ### Exercise 4
# # Number of men and women in congress by state. Hint: you will use the groupby and size methods to complete this task.
# # --------------------------------------------------------------------------------

# # Your code here...



# # --------------------------------------------------------------------------------
# # ### Exercise 5
# # Output the states with the most representatives in the house. Hint: you will use the groupby and size methods to complete this task.
# # --------------------------------------------------------------------------------

# # your code here...



# # --------------------------------------------------------------------------------
# # ###  Exercise 6
# # Create a chart of the number of people in the house of representatives by state
# # --------------------------------------------------------------------------------

# # your code here...