
# # ----------------------------------------------------------------
# # Course: EECS 110, Northwestern University
# # Term: Winter 2019
# # Autogenerated from: "../lectures/lecture_15/answers/Jupyter YouTube.ipynb"
# # 
# # Note: Each example is commented out. To uncomment, highlight
# # the area you want to uncomment and type "cmd /" (which both adds
# # and removes comments).
# # ----------------------------------------------------------------

# from apis import youtube
# from apis import utilities
# from pprint import pprint
# from IPython.display import HTML

# help(youtube)
# help(utilities)
# videos = youtube.get_videos('cats')
# pprint(videos)
# df = utilities.get_dataframe(videos)
# df
# df[['title', 'share_url', 'thumb_url', 'embed_url']]
# HTML(youtube.get_video_player_html('https://www.youtube.com/embed/SHQ-TFqnUnQ'))