
# # ----------------------------------------------------------------
# # Course: EECS 110, Northwestern University
# # Term: Winter 2019
# # Autogenerated from: "../lectures/lecture_15/notebooks/Jupyter Spotify Practice.ipynb"
# # 
# # Note: Each example is commented out. To uncomment, highlight
# # the area you want to uncomment and type "cmd /" (which both adds
# # and removes comments).
# # ----------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # # Exercise 3: In Class Activity
# # 1. Figure out how to search for a track and...
# #   * Display matching tracks
# #   * Embed a track player
# # 2. Figure out how to search for an artist and...
# #   * Display matching artists
# #   * Display an image of each matched artist
# # 3. Figure out how to search for a playlist and...
# #   * Display matching playlists
# #   * Embed a playlist player
# # --------------------------------------------------------------------------------

# from apis import spotify
# from apis import utilities
# from pprint import pprint
# from IPython.core.display import HTML
# 
# # some formatting:
# HTML(utilities.get_jupyter_styling())
# help(spotify)
# help(utilities)
# # Just a little syntax help...
# # track_id = '18GiV1BaXzPVYpp9rmOg0E'
# # track_player = spotify.get_track_player_html(track_id)
# # display(HTML(track_player))
# track_id = '18GiV1BaXzPVYpp9rmOg0E'
# track_player = spotify.get_track_player_html(track_id)
# display(HTML(track_player))
