
# # ----------------------------------------------------------------
# # Course: EECS 110, Northwestern University
# # Term: Winter 2019
# # Autogenerated from: "../lectures/lecture_15/notebooks/Jupyter Sendgrid Practice.ipynb"
# # 
# # Note: Each example is commented out. To uncomment, highlight
# # the area you want to uncomment and type "cmd /" (which both adds
# # and removes comments).
# # ----------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # # Exercise 2: In Class Activity
# # 1. Figure out how to send an email
# # 2. Figure out how to send an email with an image in it. Here is the HTML for an image (use whatever image link you want):
# # 
# # ```html
# # <img src="https://i.scdn.co/image/eb2ed0c17353cb509c2a57265fe90dfc7c7fa592">
# # ```
# # --------------------------------------------------------------------------------

# from apis import sendgrid
# help(sendgrid)
