
# # ----------------------------------------------------------------
# # Course: EECS 110, Northwestern University
# # Term: Winter 2019
# # Autogenerated from: "../lectures/lecture_15/notebooks/Jupyter Yelp Practice.ipynb"
# # 
# # Note: Each example is commented out. To uncomment, highlight
# # the area you want to uncomment and type "cmd /" (which both adds
# # and removes comments).
# # ----------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # # Exercise 4: In Class Activity
# # 1. Figure out how to search by location and display the results
# # 2. Figure out how to search for all Italian, Japanese, and Vietnamese restaurants
# # 3. Figure out how to order your results by rating
# # 4. Figure out how to make a map of matching restaurants (using the folium module)
# # --------------------------------------------------------------------------------

# from apis import yelp
# from apis import utilities
# from pprint import pprint
# help(yelp)
# help(utilities)